name: Dependabot Auto-merge

on:
  pull_request:
    branches: [main]

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Enable auto-merge for Dependabot PRs
        if: steps.metadata.outputs.update-type == 'version-update:semver-patch'
        run: |
          if gh pr merge --auto --merge "$PR_URL"; then
            echo "✅ Auto-merge successful for patch update"
          else
            echo "⚠️ Auto-merge failed, manual review required"
            echo "This is normal for some PRs that require manual approval"
            exit 0  # Don't fail the workflow
          fi
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Run tests for Dependabot PRs
        if: steps.metadata.outputs.update-type == 'version-update:semver-minor'
        run: |
          git checkout ${{ github.head_ref }}
          npm ci
          npm run test:ci
          npm run build
